- kind: Message
  name: UserSession
  fields:
    - name: userId
      type: string
      index: 1
    - name: expirationTime
      type: number
      index: 2
- kind: NodeService
  name: Node
  remoteCalls:
    - name: GetComments
      path: /GetComments
      body: GetCommentsRequest
      importBody: ./test_data/generator/service/sub/get_comments
      response: GetCommentsResponse
      importResponse: ./test_data/generator/service/sub/get_comments
  outputClient: ./test_data/generator/service/client
  outputHandler: ./test_data/generator/service/handler
- kind: Service
  name: WebService
  path: "/web"
- kind: RemoteCallsGroup
  name: WebCalls
  service: WebService
  calls:
    - name: UploadFile
      path: /UploadFile
      authKey: su
      metadata:
        key: sd
        type: UploadFileRequestMetadata
        import: ./test_data/generator/service/sub/upload_file
      body: bytes
      response: UploadFileResponse
      importResponse: ./test_data/generator/service/sub/upload_file
  outputClient: ./test_data/generator/service/client
  outputHandler: ./test_data/generator/service/handler
